import type { Metadata } from "next";
import Header from "../src/Header";
import Footer from "../src/Footer";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Устройства",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <div className="grid grid-rows-[max-content_auto_max-content] overflow-hidden h-screen">
          <Header />
          <main className="flex">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
